blank_issues_enabled: false
contact_links:
  - name: Join my community on Discord
    url: https://discord.gg/Dn9rFtqZDg
    about: Spirit's official discord server.
  - name: Follow me on ğ• (Twitter)
    url: https://x.com/lilboyspirit
    about: Spirit's official ğ• account
  - name: Follow me on Instagram
    url: https://instagram.com/lilboyspirit
    about: Spirit's official Instagram
